module.exports = {
  types: [
    { value: 'feat', name: 'feat:     新功能' },
    { value: 'fix', name: 'fix:      修复 bug' },
    { value: 'perf', name: 'perf:     性能优化' },
    { value: 'security', name: 'security: 安全修复' },
    { value: 'refactor', name: 'refactor: 重构' },
    { value: 'docs', name: 'docs:     文档变更' },
    { value: 'style', name: 'style:    代码格式调整' },
    { value: 'test', name: 'test:     测试相关' },
    { value: 'build', name: 'build:    构建/依赖变更' },
    { value: 'ci', name: 'ci:       CI/CD 变更' },
    { value: 'chore', name: 'chore:    其他杂务' },
    { value: 'revert', name: 'revert:   回滚提交' }
  ],
  scopes: [
    'user',
    'auth',
    'order',
    'pay',
    'admin',
    'http',
    'grpc',
    'websocket',
    'middleware',
    'exception',
    'service',
    'model',
    'db',
    'migration',
    'redis',
    'cache',
    'queue',
    'crontab',
    'command',
    'event',
    'listener',
    'config',
    'logger',
    'docker',
    'deploy',
    'ci',
    'docs',
    'tests'
  ],
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix', 'refactor'],
  subjectLimit: 100
};