import {
  Play,
  Command,
  Copy,
  Download,
  FilePlus,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Minus,
  PanelBottom,
  PanelLeft,
  PencilLine,
  Plus,
  RefreshCcw,
  RefreshCw,
  Save,
  Search,
  Settings2,
  SquareStop,
  Square,
  Star,
  TerminalSquare,
  Trash2,
  Undo2,
  Unplug,
  Route,
  Upload,
  X,
  Link2
} from 'lucide-react'

export const actionIcons = {
  browse: FolderOpen,
  cancel: X,
  clear: Trash2,
  clone: Copy,
  close: X,
  commandPalette: Command,
  connect: Link2,
  delete: Trash2,
  discard: Undo2,
  disconnect: Unplug,
  download: Download,
  edit: PencilLine,
  maximizeWindow: Square,
  minimizeWindow: Minus,
  newConnection: Plus,
  newFile: FilePlus,
  newFolder: FolderPlus,
  openRemoteFiles: FolderTree,
  openSettings: Settings2,
  openTerminal: TerminalSquare,
  quickOpen: Search,
  reconnect: RefreshCcw,
  refresh: RefreshCw,
  rename: PencilLine,
  restart: RefreshCcw,
  restoreWindow: Copy,
  save: Save,
  start: Play,
  star: Star,
  stop: SquareStop,
  togglePanel: PanelBottom,
  toggleSidebar: PanelLeft,
  openPortForwards: Route,
  upload: Upload
} as const
